### ISSUE TITLE
Redis parameters

### ISSUE THREAD

**Issue by FallingSnow** [danitseitlin/redis-modules-sdk-ts#116]
Is there a way to pass parameters?
For example when I submit a query with a `$variable` is I get an error message about `missing parameters`.

Kind of like https://redisgraph.github.io/redisgraph.js/Graph.html#query

**Comment by danitseitlin** [comment]
@FallingSnow Hi, I am looking on https://oss.redislabs.com/redisgraph/commands/#graphquery and It doesn't seem aligned with what you shared. I will try to check what should be the correct syntax and update the code accordingly.
Thanks for your issue.

**Comment by danitseitlin** [comment]
@FallingSnow Can you share your exact usage?

**Comment by FallingSnow** [comment]
I'm trying to escape user input in queries I submit to the database. Some libraries provide this escape function. Considering redis returns `Missing parameters` I think it might be native to redis.

Query:
```
MATCH (p:user) WHERE p.email=$email RETURN count(p) as count
```

Response:
```
Error: RedisGraph class (GRAPH.QUERY): ReplyError: Missing parameters
```

**Comment by danitseitlin** [comment]
@FallingSnow Can you share your usage with the redis-modules-sdk?

**Comment by FallingSnow** [comment]
That is.
```ts
export default class Database extends RedisGraph {
  constructor(...args) {
    super({ port: options.databasePort, host: options.databaseHost, ...args });
  }

  async query(query: string) {
    try {
     // Throws "Error: RedisGraph class (GRAPH.QUERY): ReplyError: Missing parameters"
      return await super.query(options.databaseName, query);
    } catch (error) {
      log.error("Failed to run database query: \"%s\"\n%s", query, error);
      throw new Error("Database error. See server logs.");
    }
  }

  static escape(str) {
    return str.replace(/'/g, "\\'");
  }
}

// Doesn't work
const matches = await database.query(`MATCH (p:user) WHERE p.email=$email RETURN count(p) as count`);

// Works
const matches = await database.query(`MATCH (p:user) WHERE p.email='email@email.com' RETURN count(p) as count`);
```

**Comment by FallingSnow** [comment]
Are you unable to replicate the error with a query that has a $ (dollar sign) variable?

**Comment by danitseitlin** [comment]
@FallingSnow hi, yes i am able. Sorry for the delay i will be working on this and many issues this weekend and next week.

**Comment by danitseitlin** [comment]
@FallingSnow Hi, should have a fix soon, just running some last tests.

**Comment by FallingSnow** [comment]
Great! Thank you!
