### ISSUE TITLE
Add support for RediSearch 2.2 JSON support

### ISSUE THREAD

**Issue by gkorland** [danitseitlin/redis-modules-sdk-ts#118]
Features were added specific to JSON indexing:

**On FT.CREATE:**
- `ON JSON`
- identifier `AS` Attribute

e.g.
`FT.CREATE idx ON JSON PREFIX 1 doc: SCHEMA $.product.label AS label TEXT SORTABLE $.product.stock AS stock NUMERIC SORTABLE`

**On FT.SEARCH:**

- `RETURN` {jsonPath} `AS` {property}
e.g.
`FT.SEARCH products * RETURN 2 $.product.label AS label $.reviews.content AS reviews`

**Comment by danitseitlin** [comment]
@gkorland Thanks for the ticket, but seems like it was already done here: https://github.com/danitseitlin/redis-modules-sdk-ts/commit/50b1bababdaecf061b680301f8327935beed0271#
