### ISSUE TITLE
RediSearch (FT.SEARCH): ReplyError: Unknown argument

### ISSUE THREAD

**Issue by Legolaszstudio** [danitseitlin/redis-modules-sdk-ts#125]
Hello!

I'm using this library to search my rediSearch database. I need some special parameters in my query so I added them to my function call like so:
```js
rediSearchClient.search(
   'TrainsIndex',
    `12*`,
    {
        inFields: {
            num: 2,
            field: "tags number"
         },
        highlight: {
            tags: [{
                open: "<b>",
                close: "</b>"
            }],
        }
    }
);
```

But this query fails with the following error:
```
UnhandledPromiseRejectionWarning: Error: Redisearch class (FT.SEARCH): ReplyError: Unknown argument `TAGS` at position 5 for <main>
at Redisearch.handleError (/src/node_modules/redis-modules-sdk/lib/modules/module.base.js:76:19)
at Redisearch.<anonymous> (/src/node_modules/redis-modules-sdk/lib/modules/module.base.js:65:29)
at Generator.throw (<anonymous>)
at rejected (/src/node_modules/redis-modules-sdk/lib/modules/module.base.js:6:65)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Because Redis receives the following command:
```
"FT.SEARCH" "TrainsIndex" "12*" "INFIELDS" "2" "tags number" "HIGHLIGHT" "TAGS" "<b>" "</b>"
```
But it should be:
```
FT.SEARCH "TrainsIndex" "12*" INFIELDS 2 tags number HIGHLIGHT TAGS "<b>" "</b>"
```

I tried writing my own query with `client.sendCommand` but it resulted in the same query as what the library does, so I hope there is some kind of workaround because I couldn't find the implementation of the [multi](https://github.com/NodeRedis/node-redis/blob/master/README.md#multi-word-commands) function in this library.

**Comment by danitseitlin** [comment]
@Legolaszstudio Hi, thanks for the issue. I'll look into it soon :)
Thanks for your patience!

**Comment by Legolaszstudio** [comment]
Hey @danitseitlin !

I'm back from my holiday. If you need me to, I can look into this issue deeper and maybe try to come up with a fix, or are you managing it alone? (I would like to get back to work ASAP)

If you need anything, just ping me.
@Legolaszstudio

**Comment by danitseitlin** [comment]
@Legolaszstudio Hi, I will eventually get to finishing the fix of the bug and I know the direction fix, but if you want you are more than welcome to fix it yourself and open a PR. Just let me know what you decide.

**Comment by Legolaszstudio** [comment]
Working on it!
I will probably fix it in the following 3 days. Just relax and focus on other things :)

**Comment by danitseitlin** [comment]
@Legolaszstudio Thank you very much! merged the changes!
On the other subject, are you familiar with JSDOCS on Github pages?

**Comment by Legolaszstudio** [comment]
You're welcome, I did it for the community.
Sadly I don't know anything about Github Pages, I've only used JS and TS.
