### ISSUE TITLE
Unicode issue

### ISSUE THREAD

**Issue by hadnet** [danitseitlin/redis-modules-sdk-ts#130]
When using

```ts
await this.client.set('api:cities', '.', '{"Mingá": {"id": "18", "name": "Mingá"}}');
```
 in Redis I got this

```
{"Ming\u00c3\u00a1":{"id":"18","name":"Ming\u00c3\u00a1"}}
```

When using the redis-cli --raw I can handle keys with unicode, so I wondering how to make the set function to insert 'Mingá' as a key and not "Ming\u00c3\u00a1"??

**Comment by danitseitlin** [comment]
@hadnet Hi, Thanks for the issue. I will see if I can do something regarding the problem.

**Comment by danitseitlin** [comment]
https://github.com/luin/ioredis/issues/1427

**Comment by danitseitlin** [comment]
@hadnet Seems like this is not too possible to adjust, but you could decode the result for your usages.
Look at here for an example: https://github.com/luin/ioredis/issues/1427#issuecomment-912124347
