### ISSUE TITLE
Aggregations ill formed object

### ISSUE THREAD

**Issue by channing-froom** [danitseitlin/redis-modules-sdk-ts#132]
Iv noticed that when running aggregation that there are at least 4 possible responses from the client.aggregate method

```
// returns single value in array as number - total value of objects
[0]
```

```
// expected results with a count and an array of values
[count, ...results]
```

```
// a object with the key as the total and as object of the result
{1: {a:'hello', b: 'world'}}
```

Then today i found a new one which i have no idea what to do with.
```
{
  "3": {
    "hour": "1629284400",
    "c": "bla",
    "A": "326450",
    "STARS": "666850",
    "RINGS": "495916",
    "ANSWERS": "0",
    "MASHUPS": "0",
    "RETIRES": "0",
    "PARSED": "0",
    "VOICEMAIL": "583",
    "ERRORS": "170934",
    "TIMESTAMP": "2021-08-18T11:00:00Z",
    "CARRIER": "bla"
  },
  "hour,1629280800,c,bla,A,576620,STARS,1244434,RINGS,934051,ANSWERS,0,MASHUPS,0,RETIRES,0,PARSED,0,VOICEMAIL,1025,ERRORS,310383,TIMESTAMP,2021-08-18T10:00:00Z,CARRIER,bla": {
    "hour": "1629277200",
    "c": "bla",
    "A": "323226",
    "STARS": "558757",
    "RINGS": "442940",
    "ANSWERS": "0",
    "MASHUPS": "0",
    "RETIRES": "0",
    "PARSED": "0",
    "VOICEMAIL": "416",
    "ERRORS": "115817",
    "TIMESTAMP": "2021-08-18T09:00:00Z",
    "CARRIER": "bla"
  }
}
```

^^ ment to be 3 objects but, the first one has been inserted into the count object, the second has been inserted into the key on the 3rd object.

if you loop to identify key and item you get something like this

```
key:  3
item:  0
=============
key:  hour,1629280800,c,bla,A,576620,STARS,1244434,RINGS,934051,ANSWERS,0,MASHUPS,0,RETIRES,0,PARSED,0,VOICEMAIL,1025,ERRORS,310383,TIMESTAMP,2021-08-18T10:00:00Z,CARRIER,bla
item:  1
=============
```

**Comment by danitseitlin** [comment]
@channing-froom Looks like a bug in the function that parses the result, would you like to try and fix it?

**Comment by Legolaszstudio** [comment]
@danitseitlin Found a similar issue with the spellcheck response object, I will look into it, could you please assign me?
Thanks

**Comment by Legolaszstudio** [comment]
@channing-froom Could you please provide a test case (a list of RediSearch commands) with which I could recreate the issue?

<details>
<summary>For example:</summary>

```
FT.CREATE "idx-aggreagtetest" ON HASH PREFIX 1 "person" SCHEMA "name" TEXT "city" TEXT "gender" "TAG" "timestamp" NUMERIC SORTABLE
hset "person:1" "name" "John Doe" "city" "London" "gender" "male" "timestamp" "1631460077"
FT.AGGREGATE "idx-aggreagtetest" "*" APPLY "hour(@timestamp)" AS "hour" GROUPBY "1" "@hour"
```

</details>

Thanks in advance!

**Comment by danitseitlin** [comment]
Seems like it should've been fixed by PR #161

**Comment by Legolaszstudio** [comment]
https://github.com/danitseitlin/redis-modules-sdk-ts/pull/161/files#diff-3a12d875232710819934d0ca8f8f1afa6f25f45ef1fa26797e7e48d87d0b5b4bR1-R25
Was only related to spellcheck response objects, I didn't touch the aggregation function at all

**Comment by danitseitlin** [comment]
@ashleighplummer hi, i will check it out. IMO handling a JS object is more comfortable but i will also check out your suggestion.

**Comment by ashleighplummer** [comment]
@danitseitlin could be something like this too.

```
{
  numberOfFoundElements:  2,
  result: [
    {
      id: 1,
      name: "Some name"
    },
    {
      id: 2,
      name: "Some other name"
    }
  ]
}
```

I think you're right about working with JS objects being more comfortable. As long as it returns in a standard format I'm happy :) Hope this helps

**Comment by danitseitlin** [comment]
@ashleighplummer Thanks, it's done. I'd be happy if you let me know how turned out.
