### ISSUE TITLE
Expire keys

### ISSUE THREAD

**Issue by wazini-john** [danitseitlin/redis-modules-sdk-ts#140]
How does one expire keys in redis json. I could use redis multi. But it does not appear in the documentation

**Comment by danitseitlin** [comment]
@wazini-john Can you share what exact command you're trying to achieve?

**Comment by wazini-john** [comment]
@danitseitlin I have added this functionality using `ioredis`.
``var result = await redis.multi().set(recordID, record).expire(recordID, 3600).exec();``
I set a record  and it expires after a 1 hour

**Comment by danitseitlin** [comment]
@wazini-john Each module class contains an instance of 'ioredis', called redis.
You can reach it by doing:
```
const rejson = new ReJSON({....});
var result = await rejson.redis.multi().set(recordID, record).expire(recordID, 3600).exec();
```
Should work.

**Comment by danitseitlin** [comment]
@wazini-john You are completely correct, I am working on better docs at these moments and I hope soon you will have better details :)

**Comment by wazini-john** [comment]
@danitseitlin
1. How do I add a `password` and `username`?
2. `ioredis` does not have a `connect` Can I leave it out?
3. I am using your great lib on a cloud function. What is the best way to implement it ?

**Comment by danitseitlin** [comment]
@wazini-john Hi,
1. Yes, ioredis does not have a connect function because ioredis is initiated when the object is initialized. In order to pass a username & password to connect with, please pass { username: 'my user', password: 'my password' } as part of the `IORedis.RedisOptions` type that exists in each constructor of each module under the `options` input parameter.
2. Connect is an inner function in each module class that basically initialized the ioredis object (that's how it opens connection)
3. Depends, what are you trying to do? would you like to share? I'd be happy to assist.

**Comment by danitseitlin** [comment]
@wazini-john Also, if you have any questions, feel free to post on https://github.com/danitseitlin/redis-modules-sdk-ts/discussions, it's meant for any discussion regarding the project. That way others that will have the same questions, will be able to see it's history and conversation :)

**Comment by wazini-john** [comment]
@danitseitlin Have done so here [https://github.com/danitseitlin/redis-modules-sdk-ts/discussions/149](https://github.com/danitseitlin/redis-modules-sdk-ts/discussions/149)

**Comment by wazini-john** [comment]
In order to use expire I did as advised and ended up with 
 ```
 await recordsClient.connect();
var result = await recordsClient.redis.multi().set(recordID, record).expire(recordID, 3600).exec();
```
but the method sets the record as a `string` this leads to this error `Error: ReJSON class (JSON.GET): ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value` when I use 
```
 await recordsClient.connect();
const result = await redisClient.get(recordID)
```

Can expire be added to the `REJSON` api and can the `await recordsClient.connect();` be removed entirely as they do in `ioredis` ?

**Comment by danitseitlin** [comment]
@wazini-john You've used the wrong get, function. you should've done:
```
 await recordsClient.connect();
const result = await redisClient.redis.get(recordID)
```

**Comment by wazini-john** [comment]
I figured that later... I reopened the issues because the `set` adds the data as a string. Or are they the same thing ?

Can `multi` and `expire` be added to the main api to get reduce access to `ioredis`

Also got a question here https://github.com/danitseitlin/redis-modules-sdk-ts/issues/140#issuecomment-912957442

**Comment by danitseitlin** [comment]
@wazini-john Hi, I will see what I can do and let you know

**Comment by wazini-john** [comment]
@danitseitlin Thank You would you mind checking out this question 
https://github.com/danitseitlin/redis-modules-sdk-ts/discussions/149#discussion-3554667

**Comment by FallingSnow** [comment]
@wazini-john You should use discussions if you'd like help with how to use this library.

If you believe there is an issue or would like to see a feature added the library then use issues. Also try to open a new issue/discussion for each separate question. It may seem redundant but it helps keep a clear flow for the developer.

A good example of this is your feature request
> Can multi and expire be added to the main api to get reduce access to ioredis

which is different than the original question:
> How does one expire keys in redis json. I could use redis multi. But it does not appear in the documentation

As for the reason you've re opened this issue, all redis types are strings, no numbers. There are no other primitive data types https://redis.io/topics/data-types.

**Comment by danitseitlin** [comment]
> I figured that later... I reopened the issues because the `set` adds the data as a string. Or are they the same thing ?
> 
> Can `multi` and `expire` be added to the main api to get reduce access to `ioredis`

Regarding this, what is it you exactly want? do you want to ability to use 'Redis' commands directly while using module commands in general? would you like a separate class that only supports redis commands?

**Comment by danitseitlin** [comment]
> I figured that later... I reopened the issues because the `set` adds the data as a string. Or are they the same thing ?
> 
> 
> 
> Can `multi` and `expire` be added to the main api to get reduce access to `ioredis`

This is in progress, will probably be able to do it this in around a week. Will update you once its developed.

**Comment by wazini-john** [comment]
Sorry for the late reply but the ability to use `Redis` commands directly while using module commands would be nice

**Comment by danitseitlin** [comment]
@wazini-john This is being developed at the past last week and will be added quite soon, thanks for the patience.

**Comment by danitseitlin** [comment]
Closing this issue as duplicated of #157 which is a bit more relevant to the solution you've been asking which is almost done 🤕
