### ISSUE TITLE
TimeSeries mget() filters not working

### ISSUE THREAD

**Issue by recidive** [danitseitlin/redis-modules-sdk-ts#160]
I can't get `mget()` to work properly.

When I try to run this query:

`TS.MGET FILTER foo=bar x=(a,b,c)`

this way:

`ts.mget('foo=bar x=(a,b,c)')`

it returns an error:

`Error: RedisTimeSeries class (TS.MGET): ReplyError: ERR TSDB: failed parsing labels`

And this query:

`TS.MGET FILTER foo=bar x=z`

as:

`ts.mget('foo=bar x=z')`

it returns an empty array. Not the same 12 results I get in the cli.

With a single label filter it works.

I tried a little debugging but couldn't figure this out. It looks like a critical one.

Thanks!

**Comment by danitseitlin** [comment]
@recidive Hi, thanks for the issue. I will get to it ASAP and update you on any news regarding it

**Comment by Strafo** [comment]
If you are using redis-cluster mget and mrange can't work on keys that are cross slot ( may return an (empty array) instead of MOVED)

**Comment by recidive** [comment]
Hi, the problem is that ioredis doesn't allow spaces in filters. Need to `split(' ')` the filters for this to work.

**Comment by recidive** [comment]
`args = args.concat(['FILTER'], filter.split(' '));` in the `mget` command does the trick.

**Comment by danitseitlin** [comment]
@recidive If you have a solution, would you like to create a PR?
