### ISSUE TITLE
Make Redisearch return full hash

### ISSUE THREAD

**Issue by wazini-john** [danitseitlin/redis-modules-sdk-ts#166]
What values do I need to add to my `client.search` to get full hash?
```
const [ count ,results] = await client.search(
      "index",
      query,
      {
        limit:{first:0,num:100},
        return: ***HERE***
      },
    );
```
All I am getting is an ID

**Comment by Legolaszstudio** [comment]
Nothing, by default all key-values should be returned.
You should omit return

**Comment by wazini-john** [comment]
Alright
Should be `const [count,ids,results]`
