### ISSUE TITLE
Using authentication

### ISSUE THREAD

**Issue by 1skonty1** [danitseitlin/redis-modules-sdk-ts#169]
Hello. I'm working on a nodejs server. How do I add authorization to this REJSON module in my app. All attempts have failed using this approach.

    const client = new ReJSON({
        host: 'localhost',
        port: REDIS_PORT_OUT,
        auth_pass: REDIS_PWD
    });

The error showing is:
[ioredis] Unhandled error event: ReplyError: NOAUTH Authentication required.

**Comment by danitseitlin** [comment]
@1skonty1 Hi, I think auth_pass needs to be password in order for this to work.

**Comment by danitseitlin** [comment]
@1skonty1 Hi, I think the `auth_pass` is not the correct key, it should be `password`. Let me know if that doesn't work.

**Comment by 1skonty1** [comment]
Thanks, password worked
