### ISSUE TITLE
Redisearch search wrong type

### ISSUE THREAD

**Issue by npdev453** [danitseitlin/redis-modules-sdk-ts#172]
Method `redis.search_module_search`
can return just one zero without array, but it is not described in his type.

``` ts
 const resultsRaw = await redis.search_module_search(idx, '@id:[30001 30001]')
```
```
RedisModules: Running command FT.SEARCH with arguments: statusIdx,@id:[30001 30001]
RedisModules: command FT.SEARCH responded with 0
```
```ts
 console.log('resultsRaw', resultsRaw)
```
```
resultsRaw 0
```

Seems like there should be 
https://github.com/danitseitlin/redis-modules-sdk-ts/blob/master/modules/redisearch/redisearch.ts#L60
```ts
Promise<[number, ...Array<string | string[] | {[key: string]: string}>]>
```
something like this:
``` ts
Promise<0 | [number, ...Array<string | string[] | {[key: string]: string}>]>
```

**Comment by danitseitlin** [comment]
@npdev453 Actually the type looks fine to me, 0 is a number so I don't see a reason to change the current type to use 0 as a value of the custom type. I'd expect the user of the module to know the expected values.

**Comment by npdev453** [comment]
@danitseitlin 

But 0 is a number that **not** in an array

I mean, why not:
`Promise < number | [number, ...Array<string | string[] | {[key: string]: string}>] >`
?

Because now compilation does not fail with error, when check `resultsRaw.map()` 

But in production it could  (with error `Uncaught TypeError: resultsRaw.map is not a function`) when function will return zero, that is really not expected according to current type.

**Comment by danitseitlin** [comment]
@npdev453 I see, can you share a case when its 0 for testing please?

**Comment by hixus** [comment]
it's number 0 when there are no results and noContent option is false.

**Comment by danitseitlin** [comment]
@hixus Thank you for your help! should be done now :)
