### ISSUE TITLE
getCommandExecutor() is deleted after redisson 3.15.1

### ISSUE THREAD

**Issue by Tiger0oo0** [danitseitlin/redis-modules-sdk-ts#174]
this project can not support the latest redisson, check that redission deletes the function getCommandExecutor()  after ver 3.15.1

**Comment by danitseitlin** [comment]
@Tiger0oo0 Thanks, will check it out ASAP

**Comment by danitseitlin** [comment]
@Tiger0oo0 Hi, can you share a link to what you're referring?

**Comment by Tiger0oo0** [comment]
@danitseitlin hi, seems i made a mistake.
