### ISSUE TITLE
Add support for RedisJSON 2.0

### ISSUE THREAD

**Issue by gkorland** [danitseitlin/redis-modules-sdk-ts#176]
Please notice all the commands can now get full jsonpath, i.e. dynamic paths that start with a `$` sign.
As a result all the commands can now return multi parts of the JSON.
see: https://oss.redis.com/redisjson/commands/

**Comment by danitseitlin** [comment]
https://github.com/RedisJSON/RedisJSON/releases/tag/v2.0.4
