### ISSUE TITLE
Allow consumers to opt out of request parsing for RediSearch

### ISSUE THREAD

**Issue by RShohoney** [danitseitlin/redis-modules-sdk-ts#193]
In some cases, it could be beneficial to allow users to configure redisearch to not parse any responses, and instead return the raw response from redis.  The user/consumer can then decide what is the best way to handle the response, for their own needs.

**Comment by danitseitlin** [comment]
@RShohoney 
```
const client = new Redisearch({
            host: 'host'
            port: 'port'
}, { returnRawResponse: true })
```
The above should give you the ability to retrieve the raw response. It's false by default so you'll to enable it like above.
