### ISSUE TITLE
What's the best way to prevent retrying

### ISSUE THREAD

**Issue by bridge-jithesh** [danitseitlin/redis-modules-sdk-ts#201]
Upon `connect()` if my Redis server is offline, the Node application keeps trying to establish the connection again and again and kills the entire thing completely. What's the best way to prevent this? I want to stop trying if the first connection is unsuccesful.
![image](https://user-images.githubusercontent.com/92576618/159916297-5fae8c39-214c-4dc5-a510-14f76ac5666a.png)

**Comment by danitseitlin** [comment]
@bridge-jithesh Hi, it seems like it's not possible ATM directly, I will add it ASAP and let you know. Thanks.

**Comment by danitseitlin** [comment]
@bridge-jithesh Actually my bad, it is supported. 
When creating a module object pass `maxRetriesPerRequest` with value of 0.
That would disable it.
Let me know if that doesn't work.
