### ISSUE TITLE
FT.AGGREGATE miss filter parameter

### ISSUE THREAD

**Issue by vunamhung** [danitseitlin/redis-modules-sdk-ts#206]
Hello,
I just test FT.AGGREGATE and see that it missing filter parameter, I hope team can fix this bug soon.
Thank you for helpful library.

**Comment by danitseitlin** [comment]
@vunamhung Thanks for the issue, will handle it ASAP

**Comment by danitseitlin** [comment]
@vunamhung Issue solved, please upgrade to the latest version of the package that has been deployed.
