### ISSUE TITLE
[QUESTION] Does redis-modules-sdk rely on node-redis ?

### ISSUE THREAD

**Issue by RupertBarrow** [danitseitlin/redis-modules-sdk-ts#207]
... or are they different implementations ?

I'm starting a new Redis project with NodeJS : what are the pros and cons of using one or the other Redis NodeJS sdk ?

**Comment by danitseitlin** [comment]
@RupertBarrow Hi 👋🏼 
Today Redis Modules SDK is using ioredis in the core of it, in the future it might have it's own redis sdk.
Redis modules SDK has support for Redis command from behind the scenes (ioredis) but it's main goal is to support an easy and friendly way to work with all the Redis modules in 1 package.

**Comment by RupertBarrow** [comment]
Thanks for the answer, Dani.
But node-redis (https://github.com/redis/node-redis/releases) is also an easy way to work with all the modules, since version 4, no ?

**Comment by danitseitlin** [comment]
@RupertBarrow I think the modules are in separate packages, while this project has all in one package.
