### ISSUE TITLE
Redisearch unwanted debug logs

### ISSUE THREAD

**Issue by anfly0** [danitseitlin/redis-modules-sdk-ts#223]
Hi!

There seems to be an issue where the Redisearch module ignores moduleOptions.showDebugLogs and emits debug messages to the log.
 
The most common messages come from [this](https://github.com/danitseitlin/redis-modules-sdk-ts/blob/master/modules/redisearch/redisearch.helpers.ts#L55) and [this](https://github.com/danitseitlin/redis-modules-sdk-ts/blob/master/modules/redisearch/redisearch.helpers.ts#L60) lines.

I guess the issue is [here](https://github.com/danitseitlin/redis-modules-sdk-ts/blob/master/modules/module.base.ts#L205), but I'm not sure I get how the log function is supposed to work. 
 But I assume that if the log level is DEBUG and moduleOptions.showDebugLogs is falsy, the message should be ignored and console.log not called.

Kind regards, and thanks for this awesome package!

**Comment by danitseitlin** [comment]
@anfly0 Hi, thanks for the issue! will check ASAP

**Comment by danitseitlin** [comment]
@anfly0 Hi, thanks for the patience. Let me know if the issue is fixed :)
