### ISSUE TITLE
add Redis Cluster support

### ISSUE THREAD

**Issue by MR4online** [danitseitlin/redis-modules-sdk-ts#95]
Hi there,

ioredis has support for Redis Cluster connections.
Currently I dont see a way to connect to Clusters with redis-modules-sdk.

may be all that has to be changed is:

/modules/module.base.ts line 24 from

```
    async connect(): Promise<void> {
        this.redis = new IORedis(this.redisOptions);
    }
```

to something like

```
    async connect(): Promise<void> {
        if (this.redisOptions.cluster) // flag tbd
           this.redis = new IORedis.Cluster(this.redisOptions);
        else
           this.redis = new IORedis(this.redisOptions);
    }
```

This should work with "default" Redis, I dont know if this will work with Redis modules and saidly cannot test it atm.

**Comment by danitseitlin** [comment]
Hi, thanks for the issue.
After a short look, today we can't support this.
The reason is that the 'Cluster' type does not support send_command function I use to initiate a command to the database.
I will need to open an issue and wait for it before this is done.

**Comment by danitseitlin** [comment]
@MR4online Hi, sorry for the delay. I am merging an addition ability to add support for ioredis cluster.
This was not yet tested in ongoing integration so I'd be happy if you could try it out and let me know if it works.
Thanks,
